In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
import numpy as np
import pandas as pd 

In [ ]:
input = np.random.rand(10000,3)
output = np.random.randint(2,size = 10000)
print(output)
corpus = pd.read_csv('/content/IMDB Dataset.csv', encoding = 'utf-8', engine = 'python', error_bad_lines=False)

[1 1 1 ... 0 0 0]


Skipping line 1615: unexpected end of data


In [ ]:
data = corpus.iloc[:,0]
data_labels = corpus.iloc[:,1]

In [ ]:
data

0       One of the other reviewers has mentioned that ...
1       A wonderful little production. <br /><br />The...
2       I thought this was a wonderful way to spend ti...
3       Basically there's a family where a little boy ...
4       Petter Mattei's "Love in the Time of Money" is...
                              ...                        
1608    If it weren't for the editing out of curse wor...
1609    I have seen The Running Man several times as I...
1610    A stuttering plot, uninteresting characters an...
1611    Yes, this movie is a real thief. It stole some...
1612    Whilst this is most definitely a well crafted ...
Name: review, Length: 1613, dtype: object

In [ ]:
data_labels

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
1608    negative
1609    positive
1610    negative
1611    negative
1612    negative
Name: sentiment, Length: 1613, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features= 200)
matrix_x = tfidf.fit_transform(data)
matrix_x


<1613x200 sparse matrix of type '<class 'numpy.float64'>'
	with 90150 stored elements in Compressed Sparse Row format>

In [ ]:
matrix_x.toarray

<bound method _cs_matrix.toarray of <1613x200 sparse matrix of type '<class 'numpy.float64'>'
	with 90150 stored elements in Compressed Sparse Row format>>

In [ ]:
set(data_labels)

{'negative', 'positive'}

In [ ]:
updated_labels = [0 if i =='negative' else 1 for i in data_labels ]
set(updated_labels)

{0, 1}

In [ ]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(matrix_x, updated_labels, shuffle = True, train_size = 0.8)

In [ ]:
test_x.toarray()

array([[0.11663205, 0.07455579, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08295792, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.03861089, 0.        , ..., 0.06423604, 0.        ,
        0.        ],
       [0.        , 0.15327156, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.06572442, 0.        ,
        0.        ]])

In [ ]:
test_x, test_y

In [ ]:

# train_x = train_x.toarray()
# test_x = test_x.toarray()
# 
# 
train_x = np.array(train_x)
test_x = np.array(test_x)

test_y = np.array(test_y)
train_y = np.array(train_y)


In [ ]:
model = Sequential()
model.add(Dense(100, activation='relu', input_shape = (200, )))
model.add(Dense(80, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(20, activation='relu'))
# model.add(Dense(10, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_100 (Dense)            (None, 100)               20100     
_________________________________________________________________
dense_101 (Dense)            (None, 80)                8080      
_________________________________________________________________
dense_102 (Dense)            (None, 50)                4050      
_________________________________________________________________
dense_103 (Dense)            (None, 20)                1020      
_________________________________________________________________
dense_104 (Dense)            (None, 1)                 21        
Total params: 33,271
Trainable params: 33,271
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [ ]:
model.fit(train_x, train_y, epochs=200, batch_size=64, validation_data=(test_x, test_y))

Epoch 1/200
21/21 [==============================] - 0s 5ms/step - loss: 0.6924 - accuracy: 0.5310 - val_loss: 0.6925 - val_accuracy: 0.5294
Epoch 2/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.5271 - val_loss: 0.6924 - val_accuracy: 0.5263
Epoch 3/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.5372 - val_loss: 0.6922 - val_accuracy: 0.5232
Epoch 4/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.5264 - val_loss: 0.6921 - val_accuracy: 0.5387
Epoch 5/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6921 - accuracy: 0.5310 - val_loss: 0.6919 - val_accuracy: 0.5387
Epoch 6/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6920 - accuracy: 0.5341 - val_loss: 0.6920 - val_accuracy: 0.5294
Epoch 7/200
21/21 [==============================] - 0s 3ms/step - loss: 0.6919 - accuracy: 0.5333 - val_loss: 0.6917 - val_accuracy: 0.5387
Epoch 8/200
2

In [ ]:
model.evaluate(test_x,test_y)

11/11 [==============================] - 0s 1ms/step - loss: 0.5272 - accuracy: 0.7554


[0.5271823406219482, 0.7554179430007935]

In [ ]:
model.predict(test_x[:10])

array([[0.6524797 ],
       [0.5146572 ],
       [0.74761295],
       [0.96063167],
       [0.9073896 ],
       [0.92752486],
       [0.7703819 ],
       [0.8307723 ],
       [0.33137235],
       [0.39888966]], dtype=float32)

In [ ]:
pred_y = model.predict_classes(test_x)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
prec = precision_score(pred_y, test_y, average = 'macro')
rec = recall_score(pred_y, test_y, average = 'macro')
f1 = f1_score(pred_y, test_y, average = 'macro')

In [ ]:
prec, rec, f1

(0.7396992888064317, 0.7812471655328799, 0.7402717695557026)